apiVersion: v1
appVersion: 7.0.1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/nodejs.png
name: angular7-example-app
version: 7.0.1
